user:
# users name
  name_maximum: 50
  name_minimum: 4
# users email
  email_maximum: 150
  email_minimum: 8
# user password
  password_minimum: 6
# gravatar
  gravatar_default_size: 50
kaminari:
  default_per_page: 10
